name: xleaf
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9.*
  - pip
  - numpy
  - gfortran
  - pre-commit
  - pytest
  - pytest-xdist
  - wheel
  - ipython
platforms:
  - linux-64
  - osx-arm64