name: run-pytest

on:
  pull_request:
  push:
    branches: [ main ]

env:
  PACKAGE: xleaf

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    
    - name: Create Linux environment and build package
      run: |
        conda create -n ${{ env.PACKAGE }} --file conda-linux-64.lock
        conda run -n ${{ env.PACKAGE }} --no-capture-output pip install .
      if: matrix.os == 'ubuntu-latest'

    - name: Create MacOS environment and build package
      shell: /bin/zsh {0}
      run: |
        conda create -n ${{ env.PACKAGE }} --file conda-osx-arm64.lock
        conda run -n ${{ env.PACKAGE }} --no-capture-output pip install .
      if: matrix.os == 'macos-latest'
    
    - name: Run pytest
      run: |
        conda run -n ${{ env.PACKAGE }} --no-capture-output pytest -n auto
