name: run-pytest

on:
  pull_request:
  push:
    branches: [ main ]

env:
  CACHE_NUMBER: 0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    
    - name: Cache environment
      uses: actions/cache@v2
      with:
        path: /usr/share/miniconda/envs/xleaf
        key: env-${{ hashFiles('conda-linux-64.lock', 'conda-osx-arm64.lock') }}-${{ env.CACHE_NUMBER }}
      id: cache
    
    - name: Create environment and build package
      run: |
        make create
      if: steps.cache.outputs.cache-hit != 'true'
    
    - name: Run pytest
      run: |
        make test
